### ISSUE TITLE
Quantity component for PDP page

### ISSUE THREAD

**Issue by anubhavg8** [montalvomiguelo/hydrogen-theme#11]
Hi @montalvomiguelo! Do you have a quantity selector component for the PDP pages? Noticed there are no quantity selector blocks in the product page. And I am trying to build one and it is not working properly.

**Comment by montalvomiguelo** [comment]
@anubhavg8 ! The hydrogen-theme is a port of Hydrogen's default theme, [lacking a quantity selector](https://hydrogen.shop/products/the-full-stack?Size=154cm&Color=Syntax). The hydrogen-theme uses the custom elements from Dawn; you should be able to port over the [quantity-input](https://github.com/Shopify/dawn/blob/d50698b3d8ffd06dff31dbf6e6c9c96f8b979509/snippets/quantity-input.liquid#L13) component from there.

**Comment by anubhavg8** [comment]
Thank you! Will try to do that :)
