### ISSUE TITLE
GitHub Integration

### ISSUE THREAD

**Issue by lukecharle** [montalvomiguelo/hydrogen-theme#6]
Great job on this, really excited to start using this. Just wondering if it will work with the [GitHub Integration](https://shopify.dev/docs/themes/tools/github)?

**Comment by lukecharle** [comment]
Okay cool, thanks! Just wondering how it would work if using an apps that injects files in `assets`, would we need to change the config to not remove on a build?

**Comment by montalvomiguelo** [comment]
@dan-gamble shared an excellent solution for this problem; it's a plugin that allows cleaning vite-generated assets only so we can keep whatever 3rd party apps are adding to the `assets` folder. It's open source!

https://www.npmjs.com/package/@by-association-only/vite-plugin-shopify-clean

We chatted about that here in https://github.com/barrel/shopify-vite/issues/68
