### ISSUE TITLE
Revive.js file comment issue

### ISSUE THREAD

**Issue by lukecharle** [montalvomiguelo/hydrogen-theme#7]
I've finally gotten around to giving this a try and noticed this in `revive.js`, it seems because of the `/*.js`, its actually treating it as a comment and therefore commenting out the `revive` function that will be needed.

Any ideas?

<img width="637" alt="Screenshot 2023-06-08 at 08 21 20" src="https://github.com/montalvomiguelo/hydrogen-theme/assets/115987937/2af538ac-d49f-4f08-9cb8-bc9c19f40afe">

**Comment by montalvomiguelo** [comment]
There are no comments in that file, prolly it's your editor?

**Comment by montalvomiguelo** [comment]
Hmm, something is going on in your editor. Have you been able to check the settings?

**Comment by lukecharle** [comment]
I don't believe this was editor settings, just simply a javascript file reading `/*` as a comment, as a solution I updated to the below. Adding a backslash to escape it and break the commenting, and finally adding ignore for ESLint and Prettior so it didn't complain about the backslash

```
// prettier-ignore
// eslint-disable-next-line no-useless-escape
export const islands = import.meta.glob('@/islands/\*.js')
```
