### ISSUE TITLE
Using fonts from assets

### ISSUE THREAD

**Issue by lukecharle** [montalvomiguelo/hydrogen-theme#8]
Me again..so I've added the `cleanup` plugin to avoid any files getting removed from the assets folder, all good.

Just wondering what the best/correct way to reference them now as this doesn't seem to work? Not sure if I'm not linking to them correctly? Is there a correct way to reference them to them when in the assets folder as its trying to access the `frontend` folder

<img width="437" alt="Screenshot 2023-06-27 at 13 59 07" src="https://github.com/montalvomiguelo/hydrogen-theme/assets/115987937/649f57aa-0105-4d6d-99b1-268ce9f8cf80">

<img width="1711" alt="Screenshot 2023-06-27 at 13 54 01" src="https://github.com/montalvomiguelo/hydrogen-theme/assets/115987937/5d4a29fc-dcef-4220-8e31-21b8851a2dc3">

**Comment by montalvomiguelo** [comment]
Hi @lukecharle :)

The font could be loaded from a liquid file e.g. theme.liquid using [@font-face ](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face) + the [asset_url](https://shopify.dev/docs/api/liquid/filters/asset_url) filter. Then it could be assigned to a CSS variable that you can use in your tailwind config file.

```liquid
<style>
@font-face {
  font-family: 'My Cool Font',
  font-display: 'swap',
  src: url("{{ 'my-cool-font.woff2' | asset_url }}") format('woff2'),
       url("{{ 'my-cool-font.woff' | asset_url }}") format('woff');
}

:root {
  --font-body-family: 'My Cool Font', sans-serif;
}
</style>
```
