### ISSUE TITLE
Adding media files in the asset folder. 

### ISSUE THREAD

**Issue by anubhavg8** [montalvomiguelo/hydrogen-theme#9]
Wanted to get an idea how to add media files in the repository? Is the best practice to upload it on Shopify and show the images there over keeping them in the repository?

**Comment by tylerhellner** [comment]
I would recommend adding them to Content > Files in the Shopify Admin and then referencing them wherever you need the file. That will allow you to use the appropriate liquid filters to deliver the assets from Shopify's CDN, which can yield a big boost in performance.

- [Shopify Admin > Files](https://help.shopify.com/en/manual/shopify-admin/productivity-tools/file-uploads)
- [Shopify CDN](https://shopify.dev/docs/themes/best-practices/performance/platform#shopify-cdn)

**Comment by anubhavg8** [comment]
Thanks @tylerhellner! I am using both Option 1 and Option 2 with  `emptyOutDir: false` in the vite.config.js. I am yet to try it if it works properly but seems to be okay for now.
